# Generated by Django 3.0.6 on 2020-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolibrary', '0002_auto_20200521_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FilePathField(path='static/img'),
        ),
    ]
