# Generated by Django 3.0.6 on 2020-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolibrary', '0003_auto_20200521_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FilePathField(path='static/'),
        ),
    ]
